config/routes.rb
Rails.application.routes.draw do

# ユーザーログイン
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions',
  omniauth_callbacks: "omniauth_callbacks"
}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in' => "user/sessions#guest_sign_in"
  end


#ユーザー側
  root to: "homes#top"
  get '/about' => "homes#about"
  get '/privacy_policy' => "homes#privacy_policy"
  get '/line' => "homes#line"
  # LINEbotのリクエスト処理
  post '/callback' => 'linebot#callback'
  # 退会確認画面
  get  '/users/check' => 'users#check', as: 'check_user'
  # 論理削除用のルーティング
  patch  '/users/withdraw' => 'users#withdraw'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # フォロー一覧
    get :followers, on: :member #フォロワー一覧
  end
  # ransackの検索
  get "/search" => "searches#search"
  resources :groups do
  get 'groups/list' => 'groups#list'
  get '/group_member' => 'groups#group_member'
    resource :group_user, only: [:create, :destroy]
  end
  resource :group_post, only: [:create]
  resources :categories, only: [:show]
  resources :goals, only: [:new, :edit, :show, :index, :create, :destroy, :update] do
  patch 'goal/lookback_add' => "goals#lookback_add"
  patch 'goal/status_update' => "goals#status_update"
    resource :cheers, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create, :destroy]
  # resources :notifications, only: [:index] do
  #   collection do
  #     post :update_checked
  #   end
  # end
  resources :reports, only: [:new, :create]

#管理者側
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :reports, only: [:index, :show, :update] do
      resources :comments, only: [:destroy]
    end
  end
end

app/models/group_post.rb
class GroupPost < ApplicationRecord
  belongs_to :group
  belongs_to :user

  has_rich_text :content
  validates :content, presence: true

end

app/controllers/group_posts_controller.rb
class GroupPostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_post][:group_id])
    @group_post = @group.group_posts.new(group_post_params)
    @group_post.user = current_user

    if @group_post.save
      redirect_to group_path(@group_post.group)
    else
      @groupposts = GroupPost.where(group_id: @group.id).all.order(created_at: :asc)
      render template: "groups/show"
    end
  end

  private
    def group_post_params
      params.require(:group_post).permit(:content)
    end

end

app/helpers/group_posts_helper.rb
module GroupPostsHelper
end

app/views/group_posts/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with model: group_post, url: group_post_path, method: :post do |f| %>
        <%= f.label :content, '新規投稿', class: 'col-sm-3 col-form-label' %>
        <%= f.rich_text_area :content %>
        <%= f.hidden_field :group_id, value: group.id %><br>
        <div class="text-center">
          <%= f.submit '投稿する', class: 'btn btn-secondary text-center rounded-pill' %>
        </div>
    <% end %>
  </div>
</div>

app/views/group_posts/_index.html.erb
<div class="card">
  <div class="card-body">
    <div class="post-overflow">
    <% if groupposts.present? %>
      <% groupposts.each do |grouppost| %>
      <div class="row">
        <div class="col-3">
          <%= image_tag grouppost.user.get_profile_image, size: '30x30', style: 'border-radius: 25%' %>
          <%= link_to grouppost.user.nickname, user_path(grouppost.user) %>
        </div>
        <div class="col-7">
          <%= grouppost.content %>
        </div>
        <div class="col-2">
          <%= time_ago_in_words(grouppost.created_at) %>前
        </div>
      </div>
        <hr>
      <% end %>
    <% else %>
      <strong>まだ投稿はありません。新しい投稿をしてみましょう！</strong>
    <% end %>

    </div>

  </div>
</div>