config/routes.rb
Rails.application.routes.draw do

# ユーザーログイン
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions',
  omniauth_callbacks: "omniauth_callbacks"
}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in' => "user/sessions#guest_sign_in"
  end


#ユーザー側
  root to: "homes#top"
  get '/about' => "homes#about"
  get '/privacy_policy' => "homes#privacy_policy"
  get '/line' => "homes#line"
  # LINEbotのリクエスト処理
  post '/callback' => 'linebot#callback'
  # 退会確認画面
  get  '/users/check' => 'users#check', as: 'check_user'
  # 論理削除用のルーティング
  patch  '/users/withdraw' => 'users#withdraw'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # フォロー一覧
    get :followers, on: :member #フォロワー一覧
  end
  # ransackの検索
  get "/search" => "searches#search"
  resources :groups do
  get 'groups/list' => 'groups#list'
  get '/group_member' => 'groups#group_member'
    resource :group_user, only: [:create, :destroy]
  end
  resource :group_post, only: [:create]
  resources :categories, only: [:show]
  resources :goals, only: [:new, :edit, :show, :index, :create, :destroy, :update] do
  patch 'goal/lookback_add' => "goals#lookback_add"
  patch 'goal/status_update' => "goals#status_update"
    resource :cheers, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create, :destroy]
  # resources :notifications, only: [:index] do
  #   collection do
  #     post :update_checked
  #   end
  # end
  resources :reports, only: [:new, :create]

#管理者側
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :reports, only: [:index, :show, :update] do
      resources :comments, only: [:destroy]
    end
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: "DESC") }

  belongs_to :goal, optional: true
  belongs_to :comment, optional: true
  belongs_to :cheer, optional: true
  belongs_to :relationship, optional: true

  belongs_to :visitor, class_name: "User", foreign_key: "visitor_id", optional: true
  belongs_to :visited, class_name: "User", foreign_key: "visited_id", optional: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @notices = current_user.passive_notifications.order(created_at: :desc)
    @unchecked_notifications = @notices.where(is_checked: false)if @notices.present?

    # 確認済みの通知を取得
    @checked_notifications = @notices.where(is_checked: true).limit(20)

    # 通知を確認済みに更新
    current_user.passive_notifications.update_all(is_checked: true)
    # render partial: "index"
  end

  def update_checked
    current_user.passive_notifications.update_all(is_checked: true)

  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications = current_user.passive_notifications.where(is_checked: false)
  end
end

app/views/notifications/_index.html.erb
<%
    @notices = current_user.passive_notifications.order(created_at: :desc)
    @unchecked_notifications = @notices.where(is_checked: false)

    # 確認済みの通知を取得
    @checked_notifications = @notices.where(is_checked: true).limit(20)

    # 通知を確認済みに更新
    current_user.passive_notifications.update_all(is_checked: true)
%>
<% notifications = @unchecked_notifications.where.not(visitor_id: current_user.id) %>
<% if (@unchecked_notifications.present? && @unchecked_notifications.any?) || (@checked_notifications.present? && @checked_notifications.any?) %>
  <% if @unchecked_notifications.present? %>
    <%= render "notifications/notification", notifications: @unchecked_notifications %>
  <% end %>

  <% if @checked_notifications.present? %>
    <%= render "notifications/notification", notifications: @checked_notifications %>
  <% end %>
<% else %>
  <p>通知はありません</p>
<% end %>

app/views/notifications/_notification.html.erb
<% notifications.each do |notification| %>
  <% visitor = notification.visitor %>
  <% visited = notification.visited %>
  <div class="col-md-12 mx-auto notification-container">
    <div class="notification-box d-flex align-items-center">
      <div class="notification-icon">
        <%= link_to user_path(visitor), data: { turbolinks: false } do %>
          <%= image_tag visitor.get_profile_image, size: '40x40', class: 'rounded-circle mr-3' %>
        <% end %>
      </div>

      <!-- 通知の種類に応じて表示内容を切り替え -->

      <!-- フォロー通知の場合 -->
      <% if notification.action == 'follow'  %>
        <strong><%= visitor.nickname %></strong>さんがあなたをフォローしました

      <!-- 投稿がいいねされた通知の場合 -->

      <% elsif notification.goal && notification.action == 'cheer_goal' %>
        <%= link_to goal_path(notification.goal) do %>
          <strong><%= visitor.nickname %></strong>さんが<strong><%= truncate(notification.goal.title, length: 10) %></strong>の目標を応援しました
        <% end %>

      <!-- コメントが投稿された通知の場合 -->
      <% elsif notification.action ==  'comment' %>
        <!-- 自分自身の投稿へのコメントの場合 -->
        <% if notification.goal && notification.goal.user_id == visited.id %>
          <%= link_to goal_path(notification.goal) do %>
            <strong><%= visitor.nickname %></strong>さんが<strong><%= truncate(notification.goal.title, length: 10) %></strong>の目標にコメントしました
            <% comment = Comment.find_by(id: notification.comment_id) %>
            <div class="notification-comment">
              <%#= truncate(comment, length: 30) %>
            </div>
          <% end %>

        <!-- 投稿者が異なり自身がコメントした投稿に他のユーザーがコメントした場合 -->
        <% else %>
          <span>
            <% if notification.goal %>
              <%= link_to goal_path(notification.goal) do %>
                <strong><%= visitor.nickname %></strong>さんが<strong><%= notification.goal.user.nickname + 'さんの投稿' %></strong>にコメントしました
                <% comment = Comment.find_by(id: notification.comment_id) %>
                <div class="notification-comment">
                  <%#= truncate(comment, length: 30) %>
                </div>
              <% end %>
            <% end %>
          </span>
        <% end %>
      <% end %>

    </div>
    <div class="small text-muted text-right">
      <%= time_ago_in_words(notification.created_at).upcase %>前
    </div>
  </div>
<% end %>