config/routes.rb
Rails.application.routes.draw do

# ユーザーログイン
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions',
  omniauth_callbacks: "omniauth_callbacks"
}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in' => "user/sessions#guest_sign_in"
  end


#ユーザー側
  root to: "homes#top"
  get '/about' => "homes#about"
  get '/privacy_policy' => "homes#privacy_policy"
  get '/line' => "homes#line"
  # LINEbotのリクエスト処理
  post '/callback' => 'linebot#callback'
  # 退会確認画面
  get  '/users/check' => 'users#check', as: 'check_user'
  # 論理削除用のルーティング
  patch  '/users/withdraw' => 'users#withdraw'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # フォロー一覧
    get :followers, on: :member #フォロワー一覧
  end
  # ransackの検索
  get "/search" => "searches#search"
  resources :groups do
  get 'groups/list' => 'groups#list'
  get '/group_member' => 'groups#group_member'
    resource :group_user, only: [:create, :destroy]
  end
  resource :group_post, only: [:create]
  resources :categories, only: [:show]
  resources :goals, only: [:new, :edit, :show, :index, :create, :destroy, :update] do
  patch 'goal/lookback_add' => "goals#lookback_add"
  patch 'goal/status_update' => "goals#status_update"
    resource :cheers, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create, :destroy]
  # resources :notifications, only: [:index] do
  #   collection do
  #     post :update_checked
  #   end
  # end
  resources :reports, only: [:new, :create]

#管理者側
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :reports, only: [:index, :show, :update] do
      resources :comments, only: [:destroy]
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :group_posts
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  #バリデーション
  validates :name, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 140 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 before_action :authenticate_user!, except: [:index, :show]
 before_action :owner?, only: [:edit, :update, :destroy]

  #グループの新規登録
  def new
    @group = Group.new
  end
  #グループの作成
  def create
    @group = Group.new(group_params)
    @group.owner = current_user
    if @group.save
      @group.users << current_user
      redirect_to group_path(@group.id)
      flash[:notice] = "新規グループを作成しました"
    else
      render :new
    end
  end
  #グループ一覧
  def index
    @groups = Group.all.page(params[:page]).per(10).order(created_at: :desc)
  end
  #ログインユーザーの参加グループ一覧
  def list
    @user = User.find(current_user.id)
    @groups = @user.groups.page(params[:page]).per(10).order(created_at: :desc)
  end
  #グループ詳細ページ、投稿など
  def show
    @group = Group.find(params[:id])
    @groupposts = GroupPost.where(group_id: @group.id).all.order(created_at: :desc)
    @group_post = GroupPost.new
  end
  #グループの編集(オーナーのみ可能)
  def edit
    @group = Group.find(params[:id])
  end
  #グループの情報更新
  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group.id)
      flash[:notice] = "グループ情報を更新しました"
    else
      render :edit
    end
  end

  def destroy
    group = Group.find(params[:id])
    group.destroy
    flash[:notice] = "グループの削除に成功しました"
    redirect_to groups_path
  end
  #グループ内のメンバー一覧、フォロー可能
  def group_member
    @group = Group.find(params[:group_id])
    @users = @group.users.page(params[:page]).per(10)
  end

  private

  def group_params
    params.require(:group).permit(:name, :description)
  end
  def group_post_params
    params.require(:group_post).permit(:content)
  end
  #グループの作成者(オーナー)か
  def owner?
   group = Group.find(params[:id])
   if group.owner != current_user
     redirect_to group_path(group.id)
   end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="row">
<h1 class="text-light text-center">グループ編集画面</h1>
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @group do |f| %>
          <% if @group.errors.any? %>
            <div id="error_explanation">
            <% @group.errors.full_messages.each do |message| %>
              <div class="alert alert-danger" role="alert">
                <strong>以下は必須項目です</strong>
                <ul>
                  <li><%= message %></li>
                </ul>
              </div>
            <% end %>
            </div>
          <% end %>
          <div class="field">
            <%= f.label :name, "グループ名" %>
            <%= f.text_field :name, autofocus: true, class: "shadow-sm form-control" %>
          </div>
          <div class="field">
            <%= f.label :description, "グループの説明" %>
            <%= f.text_area :description, class: "shadow-sm form-control" %>
          </div>
          <br>
          <div class="actions text-center">
            <%= f.submit "保存する", class: "shadow btn btn-secondary rounded-pill" %>
          </div>
        <% end %>
        <%= link_to "戻る", group_path(@group.id), style: "text-decoration:none;"%>
      </div>
    </div>
  </div>
</div>

app/views/groups/group_member.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
  <h1 class="text-center text-light">グループメンバー</h1>
  <div class="card">
    <div class="card-body">
      <table class="table">
        <tr>
          <th>ユーザー名</th>
          <th>自己紹介</th>
          <th>フォロー情報</th>
        </tr>
        <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user.nickname, user_path(user), style: "text-decoration:none;" %>
          </td>
          <td>
            <%= truncate(user.introduction, length: 35) %>
          </td>
          <td>
            <div id="relationship_<%= user.id %>">
              <%= render "users/relationship", user: user %>
            </div>
          </td>
        </tr>
        <% end %>
      </table>
      <%= paginate @users, theme: 'bootstrap-5', class: "paginations" %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="text-center text-light">グループ一覧</h1>
    <div class="card">
      <div class="card-body">
        <div class="text-center">
          <% if user_signed_in? %>
            <%= link_to '新しいグループを作成', new_group_path, class: "btn btn-outline-success rounded-pill" %>
          <% end %>
        </div><hr>
          <div class="row">
            <div class="col-3">
              グループ名
            </div>
            <div class="col-6">
              グループ説明
            </div>
            <div class="col-3">
              参加人数
            </div>
          </div>
        <% @groups.each do |group| %>
          <hr>
          <div class="row">
            <div class="col-3">
              <%= link_to group.name, group_path(group.id), style: "text-decoration:none;" %>
            </div>
            <div class="col-6">
              <%= truncate(group.description, length: 50) %>
            </div>
            <div class="col-3">
              <%= group.users.count %>人
            </div>
          </div>
        <% end %>
        <%= paginate @groups, theme: 'bootstrap-5', class: "paginations" %>
      </div>
    </div>
  </div>
</div>

app/views/groups/list.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="text-center text-light"><%= @user.nickname %>さんの参加しているグループ</h1>
    <div class="card">
      <div class="card-body">
        <div class="row">
            <div class="col-3">
              グループ名
            </div>
            <div class="col-6">
              グループ説明
            </div>
            <div class="col-3">
              グループメンバー
            </div>
        </div>
        <% @groups.each do |group| %>
          <hr>
          <div class="row">
            <div class="col-3">
              <%= link_to group.name, group_path(group.id), style: "text-decoration:none;" %>
            </div>
            <div class="col-6">
              <%= truncate(group.description, length: 50)  %>
            </div>
            <div class="col-3">
              <%= link_to group_group_member_path(group.id), style: "text-decoration:none;" do %>
                <%= group.users.count %>人
              <% end %>
            </div>
          </div>
        <% end %>
        <%= paginate @groups, theme: 'bootstrap-5', class: "paginations" %>
      </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="row">
<h1 class="text-light text-center">グループの作成</h1>
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @group do |f| %>
          <% if @group.errors.any? %>
            <div class="alert alert-danger" role="alert">
              <div id="error_explanation">
                <strong>以下は必須項目です</strong>
                <ul>
                  <% @group.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :name, "グループ名" %>
            <%= f.text_field :name, autofocus: true, class: "shadow-sm form-control" %>
          </div>

          <div class="field">
            <%= f.label :description, "グループの説明" %>
            <%= f.text_area :description, class: "shadow-sm form-control" %>
          </div>
          <br>
          <div class="actions text-center">
            <%= f.submit "作成する", class: "shadow btn btn-secondary rounded-pill" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
    <h1><span class="title-marker"><%= @group.name %></span></h1>
    <p>グループオーナー：<%= @group.owner.nickname %></p>
    <p><strong>説明:</strong> <%= @group.description %></p>
      <% if user_signed_in? %>
        <% if @group.owner == current_user %>
          <%= link_to "グループを編集する", edit_group_path(@group.id), class: "btn btn-outline-success rounded-pill" %>
          <%= link_to "グループを削除する", group_path(@group.id), method: :delete, data: {confirm: "本当にグループを消しますか？"}, class: "btn btn-outline-danger rounded-pill" %>
        <% elsif @group.group_users.exists?(user_id: current_user.id) %>
         <%= link_to "脱退する",  group_group_user_path(@group), method: :delete, class: "btn btn-outline-danger rounded-pill" %>
       <% else %>
         <%= link_to "参加する", group_group_user_path(@group), method: :post, class: "btn btn-outline-primary rounded-pill" %>
       <% end %>
     <% end %>


    <%= link_to '一覧に戻る', groups_path, class: "btn btn-outline-secondary rounded-pill" %>
      </div>
    </div>

    <% if @group.users.include?(current_user) %>
      <%= render partial: "group_posts/form", locals: { group_post: @group_post, group: @group } %>
      <%= render "group_posts/index", groupposts: @groupposts %>
    <% else %>
    <% end %>
  </div>
</div>