config/routes.rb
Rails.application.routes.draw do

# ユーザーログイン
devise_for :users, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions',
  omniauth_callbacks: "omniauth_callbacks"
}
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    post 'users/guest_sign_in' => "user/sessions#guest_sign_in"
  end


#ユーザー側
  root to: "homes#top"
  get '/about' => "homes#about"
  get '/privacy_policy' => "homes#privacy_policy"
  get '/line' => "homes#line"
  # LINEbotのリクエスト処理
  post '/callback' => 'linebot#callback'
  # 退会確認画面
  get  '/users/check' => 'users#check', as: 'check_user'
  # 論理削除用のルーティング
  patch  '/users/withdraw' => 'users#withdraw'
  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # フォロー一覧
    get :followers, on: :member #フォロワー一覧
  end
  # ransackの検索
  get "/search" => "searches#search"
  resources :groups do
  get 'groups/list' => 'groups#list'
  get '/group_member' => 'groups#group_member'
    resource :group_user, only: [:create, :destroy]
  end
  resource :group_post, only: [:create]
  resources :categories, only: [:show]
  resources :goals, only: [:new, :edit, :show, :index, :create, :destroy, :update] do
  patch 'goal/lookback_add' => "goals#lookback_add"
  patch 'goal/status_update' => "goals#status_update"
    resource :cheers, only: [:create, :destroy, :index]
    resources :comments, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create, :destroy]
  # resources :notifications, only: [:index] do
  #   collection do
  #     post :update_checked
  #   end
  # end
  resources :reports, only: [:new, :create]

#管理者側
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :categories, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :show, :destroy]
    resources :reports, only: [:index, :show, :update] do
      resources :comments, only: [:destroy]
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  
# 通報者を示す関連付け
  belongs_to :reporter, class_name: "User", foreign_key: "reporter_id"
  
  # 通報対象を示す関連付け
  belongs_to :reported, class_name: "User", foreign_key: "reported_id"
  
  # 通報対象のコンテンツを示す多様性（Polymorphic）関連付け
  belongs_to :content, polymorphic: true
  
  # 通報理由の列挙型（Enum）
  enum reason: {
    malicious_expression: 0,      # 悪意のある表現
    inappropriate_content: 1,     # 不適切なコンテンツ
    misinformation: 2,            # 誤った情報
    commercial_purposes: 3,       # 商業目的
    spam: 4,                      # スパム
    other: 5                      # その他
  }
  enum status: { waiting: 0, keep: 1, finish: 2 }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @reports = Report.all.order(created_at: :desc).page(params[:page]).per(10)
  end

  def show
    @report = Report.find(params[:id])
    @comment = @report.content
  end

  def update
    @report = Report.find(params[:id])
    if @report.update!(report_params) #ストロングパラメータを通して更新
      flash[:notice] = "対応ステータスを更新しました。"
      redirect_to request.referer
    end
  end

  private

  def report_params
    params.require(:report).permit(:status)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  # ユーザーが新しい報告を作成するページへアクセスするためのアクション
  def new
    @report = Report.new
    render :layout => false
  end

  # ユーザーからの報告を作成するアクション
  def create
    # ユーザーが報告する対象の種類とIDを取得
    content_type = params[:report][:content_type]
    content_id = params[:report][:content_id]

    # 対象のコンテンツをデータベースから取得
    @content = content_type.constantize.find(content_id)

    # 対象のコンテンツが存在する場合
    if @content
      # 新しい報告オブジェクトを作成
      @report = Report.new(report_params)

      # 報告者と報告対象を設定
      @report.reporter = current_user
      @report.reported = @content.user

      # 報告をデータベースに保存
      if @report.save
        respond_to do |format|
          format.js { render "create_success" } # 成功時のレスポンスを返す
        end
      else
        respond_to do |format|
          format.js { render "create_failure" } # 失敗時のレスポンスを返す
        end
      end
    end

  rescue ActiveRecord::NotNullViolation => e
    # NOT NULL 制約違反が発生した場合もエラー処理
    respond_to do |format|
      format.js { render "create_failure", status: :unprocessable_entity } # エラーレスポンスを返す
    end
  end

  private

  # コンテンツをデータベースから取得するメソッド
  def find_content(content_type, content_id)
    content_class = content_type.classify.constantize
    content_class.find_by(id: content_id)
  end

  # 報告のパラメーターを安全に受け取るためのメソッド
  def report_params
    params.require(:report).permit(:content_type, :content_id, :reason)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/index.html.erb
<h1 class="text-light text-center">通報一覧</h1>
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <div class="card">
      <div class="card-body">
        <table class="table">
          <tr>
            <th>通報No.</th>
            <th>通報者</th>
            <th>通報された人</th>
            <th>通報内容</th>
            <th>対処</th>
          </tr>
            <% @reports.each do |report| %>
          <tr>
            <td><%= link_to report.id, admin_report_path(report) %></td>
            <td><%= report.reporter.nickname %></td>
            <td><%= report.reported.nickname %></td>
            <td><%= report.reason_i18n %></td>
            <td><%= report.status_i18n %></td>
          </tr>
          　<% end %>
        </table>
        <div class="text-center">
          <%= paginate @reports, theme: 'bootstrap-5', nav_class: "d-inline-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="row">
  <div class="col-2"></div>
  <div class="col-8">
    <h1 class="page-title text-light text-center">通報詳細</h3>
    <div class="card">
      <div class="card-body">
        <table class="table">
          <tbody>
            <tr>
              <td>通報ID</td>
              <td><%= link_to @report.id %></td>
            </tr>
            <tr>
              <td>会員名</td>
              <td><%= link_to @report.reported.nickname, edit_admin_user_path(@report.reported.id) %></td>
            </tr>
            <tr>
              <td>理由</td>
              <td><%= @report.reason_i18n %></td>
            </tr>
            <tr>
              <td>通報内容</td>
              <% if @comment.present? %>
                <td><%= @report.content_type.classify.constantize.find(@report.content_id).body %></td>
                <td><%= link_to "削除", admin_report_comment_path(@report.id,@comment.id), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: '本当に削除しますか？' }  %></td>
              <% else %>
                コメントは削除されました
              <% end %>
            </tr>
            <tr>
              <td>通報者</td>
              <td><%= @report.reporter.nickname %></td>
            </tr>
            <tr>
              <td>対応ステータス</td>
              <td>
                <%= @report.status_i18n %>
                <%= form_with model:@report, url: admin_report_path(@report), method: :patch, local: true do |f| %>
                  <div class="form-inline">
                    <div class="input-group">
                      <%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] }, {}, {class: "form-control"}%>
                      <%= f.submit '更新', class: "btn btn-sm btn-secondary" %>
                    </div>
                  </div>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>